export const FETCH_USERS_START = "FETCH_USERS_START";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";
export const FETCH_USERS_DEFAULT = "FETCH_USERS_DEFAULT";



export const FETCH_USER_PAGE_START = "FETCH_USER_PAGE_START";
export const FETCH_USER_PAGE_SUCCESS = "FETCH_USER_PAGE_SUCCESS";
export const FETCH_USER_PAGE_ERROR = "FETCH_USER_PAGE_ERROR";
export const FETCH_USER_PAGE_DEFAULT = "FETCH_USER_PAGE_DEFAULT";